### ISSUE TITLE
Fix order of certs in bundle

### ISSUE THREAD

**Issue by devth** [UKHomeOffice/vaultjks#7]
[RFC 5246](https://tools.ietf.org/html/rfc5246#section-7.4.2) says:

>  certificate_list
      This is a sequence (chain) of certificates.  The sender's
      certificate MUST come first in the list.  Each following
      certificate MUST directly certify the one preceding it.  Because
      certificate validation requires that root keys be distributed
      independently, the self-signed certificate that specifies the root
      certificate authority MAY be omitted from the chain, under the
      assumption that the remote end must already possess it in order to
      validate it in any case.

That means [this line](https://github.com/UKHomeOffice/vaultjks/blob/master/run.sh#L85) is concatenating them in reverse. Apparently it doesn't matter when using the bundle to gen a keystore, but it does matter if you try to use `bundle.pem` directly.

Found via [StackOverflow](https://serverfault.com/a/476620/28019) after observing that `bundle.pem` does not work when trying to use it directly along with `key.pem`.

**Comment by vaijab** [comment]
@devth please let me know if #8 fixes the issue.
